// <auto-generated />
using System;
using IQFlowAgent.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IQFlowAgent.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310052625_AddIntakeFieldConfig")]
    partial class AddIntakeFieldConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("IQFlowAgent.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.AuthSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthMode")
                        .IsRequired();

                    b.Property<string>("LdapBaseDn");

                    b.Property<string>("LdapBindDn");

                    b.Property<string>("LdapBindPassword");

                    b.Property<int>("LdapPort");

                    b.Property<string>("LdapSearchFilter");

                    b.Property<string>("LdapServer");

                    b.Property<bool>("LdapUseSsl");

                    b.Property<int>("TenantId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("AuthSettings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.FinalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath")
                        .IsRequired();

                    b.Property<long>("FileSizeBytes");

                    b.Property<DateTime>("GeneratedAt");

                    b.Property<string>("GeneratedByName");

                    b.Property<string>("GeneratedByUserId");

                    b.Property<int>("IntakeRecordId");

                    b.Property<string>("ReportFileName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("FinalReports");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<string>("DocumentType")
                        .IsRequired();

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("FilePath")
                        .IsRequired();

                    b.Property<long?>("FileSize");

                    b.Property<int>("IntakeRecordId");

                    b.Property<int?>("IntakeTaskId");

                    b.Property<string>("SopDocumentPath");

                    b.Property<string>("TranscriptStatus")
                        .IsRequired();

                    b.Property<string>("TranscriptText");

                    b.Property<DateTime>("UploadedAt");

                    b.Property<string>("UploadedByName");

                    b.Property<string>("UploadedByUserId");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.HasIndex("IntakeTaskId");

                    b.ToTable("IntakeDocuments");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeFieldConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<int>("DisplayOrder");

                    b.Property<string>("FieldName")
                        .IsRequired();

                    b.Property<bool>("IsMandatory");

                    b.Property<bool>("IsVisible");

                    b.Property<string>("SectionName")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("IntakeFieldConfigs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnalysisResult");

                    b.Property<DateTime?>("AnalyzedAt");

                    b.Property<string>("BusinessUnit")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedByUserId");

                    b.Property<string>("Department")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("EstimatedVolumePerDay");

                    b.Property<string>("IntakeId")
                        .IsRequired();

                    b.Property<string>("Lob")
                        .IsRequired();

                    b.Property<string>("Priority")
                        .IsRequired();

                    b.Property<string>("ProcessName")
                        .IsRequired();

                    b.Property<string>("ProcessOwnerEmail")
                        .IsRequired();

                    b.Property<string>("ProcessOwnerName")
                        .IsRequired();

                    b.Property<string>("ProcessType")
                        .IsRequired();

                    b.Property<string>("SdcLots")
                        .IsRequired();

                    b.Property<string>("SiteLocation")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<DateTime?>("SubmittedAt");

                    b.Property<int>("TenantId");

                    b.Property<string>("TimeZone")
                        .IsRequired();

                    b.Property<string>("UploadedFileContentType");

                    b.Property<string>("UploadedFileName");

                    b.Property<string>("UploadedFilePath");

                    b.Property<long?>("UploadedFileSize");

                    b.HasKey("Id");

                    b.ToTable("IntakeRecords");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedByUserId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("DueDate");

                    b.Property<int>("IntakeRecordId");

                    b.Property<bool>("IsNotApplicable");

                    b.Property<string>("NaReason");

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<string>("Priority")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("TaskId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("IntakeTasks");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.LotCountryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cities")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LotName")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("LotCountryMappings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.MasterDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("MasterDepartments");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.MasterLob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("MasterLobs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.QcCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ErrorMessage");

                    b.Property<int>("IntakeRecordId");

                    b.Property<int>("OverallScore");

                    b.Property<string>("RunByUserId");

                    b.Property<string>("ScoreBreakdownJson");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("QcChecks");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.RagJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ErrorMessage");

                    b.Property<int>("IntakeRecordId");

                    b.Property<string>("NotifyUserId");

                    b.Property<int>("ProcessedFiles");

                    b.Property<DateTime?>("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("TotalFiles");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("RagJobs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.ReportFieldStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AnalyzedAt");

                    b.Property<string>("FieldKey")
                        .IsRequired();

                    b.Property<string>("FieldLabel")
                        .IsRequired();

                    b.Property<string>("FillValue");

                    b.Property<int>("IntakeRecordId");

                    b.Property<bool>("IsNA");

                    b.Property<string>("LinkedTaskId");

                    b.Property<string>("Notes");

                    b.Property<string>("Section")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("TemplatePlaceholder")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("ReportFieldStatuses");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TaskActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionType")
                        .IsRequired();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedByName");

                    b.Property<string>("CreatedByUserId");

                    b.Property<int>("IntakeTaskId");

                    b.Property<string>("NewStatus");

                    b.Property<string>("OldStatus");

                    b.HasKey("Id");

                    b.HasIndex("IntakeTaskId");

                    b.ToTable("TaskActionLogs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Slug")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TenantAiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AzureOpenAIApiKey")
                        .IsRequired();

                    b.Property<string>("AzureOpenAIApiVersion")
                        .IsRequired();

                    b.Property<string>("AzureOpenAIDeploymentName")
                        .IsRequired();

                    b.Property<string>("AzureOpenAIEndpoint")
                        .IsRequired();

                    b.Property<int>("AzureOpenAIMaxTokens");

                    b.Property<string>("AzureSpeechApiKey")
                        .IsRequired();

                    b.Property<string>("AzureSpeechRegion")
                        .IsRequired();

                    b.Property<string>("AzureStorageConnectionString")
                        .IsRequired();

                    b.Property<string>("AzureStorageContainerName")
                        .IsRequired();

                    b.Property<int>("TenantId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedByUserId");

                    b.Property<bool>("UseCountryFilterByLot");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantAiSettings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.UserTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AssignedAt");

                    b.Property<bool>("IsDefault");

                    b.Property<int>("TenantId");

                    b.Property<string>("TenantRole")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.FinalReport", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeDocument", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.IntakeTask", "Task")
                        .WithMany("Documents")
                        .HasForeignKey("IntakeTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("IntakeRecord");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.QcCheck", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.RagJob", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.ReportFieldStatus", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TaskActionLog", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeTask", "Task")
                        .WithMany("ActionLogs")
                        .HasForeignKey("IntakeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TenantAiSettings", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.UserTenant", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
