// <auto-generated />
using System;
using IQFlowAgent.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IQFlowAgent.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("IQFlowAgent.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PiiFindingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PiiFindingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PiiScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.AuthSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapBaseDn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapBindDn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapBindPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("LdapPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LdapSearchFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapServer")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LdapUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthSettings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.FinalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("FinalReports");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntakeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SopDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.HasIndex("IntakeTaskId");

                    b.ToTable("IntakeDocuments");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeFieldConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IntakeFieldConfigs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisResult")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedVolumePerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntakeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PiiMaskingLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessOwnerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessOwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SdcLots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedFileContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedFilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UploadedFileSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IntakeRecords");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("BartokSectionName");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("IntakeTasks");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.LotCountryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LotCountryMappings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.MasterDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MasterDepartments");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.MasterLob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MasterLobs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.QcCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("QcChecks");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.RagJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotifyUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("RagJobs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.ReportFieldStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplatePlaceholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRecordId");

                    b.ToTable("ReportFieldStatuses");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TaskActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntakeTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntakeTaskId");

                    b.ToTable("TaskActionLogs");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TenantAiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureOpenAIApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureOpenAIApiVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureOpenAIDeploymentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureOpenAIEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AzureOpenAIMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureOpenAIModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureOpenAIEmbeddingDeployment")
                        .IsRequired();

                    b.Property<string>("AzureDocumentIntelligenceEndpoint")
                        .IsRequired();

                    b.Property<string>("AzureDocumentIntelligenceApiKey")
                        .IsRequired();

                    b.Property<string>("AzureSearchEndpoint")
                        .IsRequired();

                    b.Property<string>("AzureSearchApiKey")
                        .IsRequired();

                    b.Property<string>("AzureSearchIndexName")
                        .IsRequired();

                    b.Property<string>("AzureSpeechApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureSpeechRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureStorageConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureStorageContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCountryFilterByLot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantAiSettings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TenantPiiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlockOnDetection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectCreditCardNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectDatesOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectEmailAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectIpAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectPassportNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectPersonNames")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectPhoneNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectSsnNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantPiiSettings");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.UserTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.FinalReport", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeDocument", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.IntakeTask", "Task")
                        .WithMany("Documents")
                        .HasForeignKey("IntakeTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("IntakeRecord");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.QcCheck", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.RagJob", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.ReportFieldStatus", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeRecord", "IntakeRecord")
                        .WithMany()
                        .HasForeignKey("IntakeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeRecord");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TaskActionLog", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.IntakeTask", "Task")
                        .WithMany("ActionLogs")
                        .HasForeignKey("IntakeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.TenantAiSettings", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.UserTenant", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IQFlowAgent.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IQFlowAgent.Web.Models.IntakeTask", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
